# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1109, 701)
        mainWindow.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        mainWindow.setPalette(palette)
        mainWindow.setIconSize(QtCore.QSize(24, 24))
        mainWindow.setDocumentMode(False)
        mainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.InputTab = QtWidgets.QWidget()
        self.InputTab.setObjectName("InputTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.InputTab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.InputTab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame_5 = QtWidgets.QFrame(self.splitter)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_5)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -126, 894, 653))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.demand_nominal_power_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.demand_nominal_power_doubleSpinBox.setMaximum(999999999.99)
        self.demand_nominal_power_doubleSpinBox.setObjectName("demand_nominal_power_doubleSpinBox")
        self.gridLayout.addWidget(self.demand_nominal_power_doubleSpinBox, 0, 1, 1, 1)
        self.demand_show_profile_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.demand_show_profile_pushButton.setObjectName("demand_show_profile_pushButton")
        self.gridLayout.addWidget(self.demand_show_profile_pushButton, 4, 0, 1, 1)
        self.start_dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.start_dateEdit.setObjectName("start_dateEdit")
        self.gridLayout.addWidget(self.start_dateEdit, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 3, 0, 1, 1)
        self.investment_years_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.investment_years_spinBox.setObjectName("investment_years_spinBox")
        self.gridLayout.addWidget(self.investment_years_spinBox, 2, 1, 1, 1)
        self.interest_rate_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.interest_rate_doubleSpinBox.setMaximum(1.0)
        self.interest_rate_doubleSpinBox.setObjectName("interest_rate_doubleSpinBox")
        self.gridLayout.addWidget(self.interest_rate_doubleSpinBox, 3, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 3, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wind_farm_show_profile_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.wind_farm_show_profile_pushButton.setObjectName("wind_farm_show_profile_pushButton")
        self.gridLayout_2.addWidget(self.wind_farm_show_profile_pushButton, 2, 0, 1, 1)
        self.wind_farm_nominal_power_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.wind_farm_nominal_power_doubleSpinBox.setMaximum(999999999.0)
        self.wind_farm_nominal_power_doubleSpinBox.setObjectName("wind_farm_nominal_power_doubleSpinBox")
        self.gridLayout_2.addWidget(self.wind_farm_nominal_power_doubleSpinBox, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.wind_farm_unitary_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.wind_farm_unitary_cost_doubleSpinBox.setMaximum(999999999.0)
        self.wind_farm_unitary_cost_doubleSpinBox.setObjectName("wind_farm_unitary_cost_doubleSpinBox")
        self.gridLayout_2.addWidget(self.wind_farm_unitary_cost_doubleSpinBox, 1, 1, 1, 1)
        self.wind_turbine_show_curve_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.wind_turbine_show_curve_pushButton.setObjectName("wind_turbine_show_curve_pushButton")
        self.gridLayout_2.addWidget(self.wind_turbine_show_curve_pushButton, 2, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.solar_farm_show_profile_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.solar_farm_show_profile_pushButton.setObjectName("solar_farm_show_profile_pushButton")
        self.gridLayout_4.addWidget(self.solar_farm_show_profile_pushButton, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 2, 1, 1)
        self.solar_farm_nominal_power_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.solar_farm_nominal_power_doubleSpinBox.setMaximum(999999999.0)
        self.solar_farm_nominal_power_doubleSpinBox.setObjectName("solar_farm_nominal_power_doubleSpinBox")
        self.gridLayout_4.addWidget(self.solar_farm_nominal_power_doubleSpinBox, 0, 1, 1, 1)
        self.solar_farm_unitary_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.solar_farm_unitary_cost_doubleSpinBox.setMaximum(999999999.0)
        self.solar_farm_unitary_cost_doubleSpinBox.setObjectName("solar_farm_unitary_cost_doubleSpinBox")
        self.gridLayout_4.addWidget(self.solar_farm_unitary_cost_doubleSpinBox, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 2, 5, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 1, 5, 1, 1)
        self.storage_max_unitary_cost_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.storage_max_unitary_cost_doubleSpinBox.setMaximum(999999999.0)
        self.storage_max_unitary_cost_doubleSpinBox.setObjectName("storage_max_unitary_cost_doubleSpinBox")
        self.gridLayout_5.addWidget(self.storage_max_unitary_cost_doubleSpinBox, 0, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.storage_min_soc_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.storage_min_soc_doubleSpinBox.setMaximum(1.0)
        self.storage_min_soc_doubleSpinBox.setObjectName("storage_min_soc_doubleSpinBox")
        self.gridLayout_5.addWidget(self.storage_min_soc_doubleSpinBox, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 2, 3, 1, 1)
        self.storage_max_nominal_energy_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.storage_max_nominal_energy_doubleSpinBox.setMaximum(999999999.0)
        self.storage_max_nominal_energy_doubleSpinBox.setObjectName("storage_max_nominal_energy_doubleSpinBox")
        self.gridLayout_5.addWidget(self.storage_max_nominal_energy_doubleSpinBox, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 5, 1, 1)
        self.storage_charge_eff_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.storage_charge_eff_doubleSpinBox.setMaximum(1.0)
        self.storage_charge_eff_doubleSpinBox.setObjectName("storage_charge_eff_doubleSpinBox")
        self.gridLayout_5.addWidget(self.storage_charge_eff_doubleSpinBox, 2, 1, 1, 1)
        self.storage_max_soc_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.storage_max_soc_doubleSpinBox.setMaximum(1.0)
        self.storage_max_soc_doubleSpinBox.setObjectName("storage_max_soc_doubleSpinBox")
        self.gridLayout_5.addWidget(self.storage_max_soc_doubleSpinBox, 1, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 2, 0, 1, 1)
        self.storage_discharge_eff_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.storage_discharge_eff_doubleSpinBox.setMaximum(1.0)
        self.storage_discharge_eff_doubleSpinBox.setObjectName("storage_discharge_eff_doubleSpinBox")
        self.gridLayout_5.addWidget(self.storage_discharge_eff_doubleSpinBox, 2, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 1, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_5)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.inputsPlot = MatplotlibWidget(self.splitter)
        self.inputsPlot.setObjectName("inputsPlot")
        self.horizontalLayout.addWidget(self.splitter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/file/ic_insert_chart_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.InputTab, icon, "")
        self.SimulationTab = QtWidgets.QWidget()
        self.SimulationTab.setObjectName("SimulationTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SimulationTab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.SimulationTab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_6 = QtWidgets.QFrame(self.splitter_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_6)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 2, 0, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_6)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.results_comboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.results_comboBox.setObjectName("results_comboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.results_comboBox)
        self.plot_results_pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.plot_results_pushButton.setObjectName("plot_results_pushButton")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.plot_results_pushButton)
        self.gridLayout_3.addWidget(self.groupBox_5, 1, 0, 1, 2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_6)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.size_simulate_pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.size_simulate_pushButton.setObjectName("size_simulate_pushButton")
        self.horizontalLayout_3.addWidget(self.size_simulate_pushButton)
        self.max_eval_spinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.max_eval_spinBox.setMinimum(10)
        self.max_eval_spinBox.setMaximum(99999999)
        self.max_eval_spinBox.setProperty("value", 100)
        self.max_eval_spinBox.setObjectName("max_eval_spinBox")
        self.horizontalLayout_3.addWidget(self.max_eval_spinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_3.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.resultsPlot = MatplotlibWidget(self.splitter_2)
        self.resultsPlot.setObjectName("resultsPlot")
        self.horizontalLayout_2.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.SimulationTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.progress_frame = QtWidgets.QFrame(self.centralwidget)
        self.progress_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_frame.setObjectName("progress_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.progress_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.progress_label = QtWidgets.QLabel(self.progress_frame)
        self.progress_label.setObjectName("progress_label")
        self.gridLayout_6.addWidget(self.progress_label, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.progress_frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_6.addWidget(self.progressBar, 1, 0, 1, 1)
        self.cancel_pushButton = QtWidgets.QPushButton(self.progress_frame)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.gridLayout_6.addWidget(self.cancel_pushButton, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.progress_frame)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1109, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuProject = QtWidgets.QMenu(self.menuBar)
        self.menuProject.setObjectName("menuProject")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        mainWindow.setMenuBar(self.menuBar)
        self.actionOpen_file = QtWidgets.QAction(mainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionSave = QtWidgets.QAction(mainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew_project = QtWidgets.QAction(mainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuProject.addAction(self.actionNew_project)
        self.menuProject.addAction(self.actionOpen_file)
        self.menuProject.addAction(self.actionSave)
        self.menuProject.addSeparator()
        self.menuAbout.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuProject.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "CopperPlate"))
        self.groupBox.setTitle(_translate("mainWindow", "Demand"))
        self.label_3.setText(_translate("mainWindow", "kW"))
        self.label_24.setText(_translate("mainWindow", "Investment years"))
        self.label.setText(_translate("mainWindow", "Start date"))
        self.label_2.setText(_translate("mainWindow", "Nominal power"))
        self.demand_show_profile_pushButton.setText(_translate("mainWindow", "Show profile"))
        self.start_dateEdit.setDisplayFormat(_translate("mainWindow", "dd/MM/yyyy"))
        self.label_25.setText(_translate("mainWindow", "Interest rate"))
        self.label_26.setText(_translate("mainWindow", "per unit"))
        self.label_27.setText(_translate("mainWindow", "Years"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Wind farm"))
        self.wind_farm_show_profile_pushButton.setText(_translate("mainWindow", "Show profile"))
        self.label_5.setText(_translate("mainWindow", "Max. nominal power"))
        self.label_10.setText(_translate("mainWindow", "€ / kW"))
        self.label_4.setText(_translate("mainWindow", "kW"))
        self.label_11.setText(_translate("mainWindow", "Unitary cost"))
        self.wind_turbine_show_curve_pushButton.setText(_translate("mainWindow", "Show wind turbine curve"))
        self.groupBox_3.setTitle(_translate("mainWindow", "Solar farm"))
        self.label_7.setText(_translate("mainWindow", "Max. nominal power"))
        self.solar_farm_show_profile_pushButton.setText(_translate("mainWindow", "Show profile"))
        self.label_6.setText(_translate("mainWindow", "kW"))
        self.label_13.setText(_translate("mainWindow", "Unitary cost"))
        self.label_12.setText(_translate("mainWindow", "€ / kW"))
        self.groupBox_4.setTitle(_translate("mainWindow", "Storage"))
        self.label_23.setText(_translate("mainWindow", "per unit"))
        self.label_19.setText(_translate("mainWindow", "per unit"))
        self.label_17.setText(_translate("mainWindow", "Max state of charge"))
        self.label_8.setText(_translate("mainWindow", "kWh"))
        self.label_9.setText(_translate("mainWindow", "Max. nominal energy"))
        self.label_22.setText(_translate("mainWindow", "Discharge efficiency"))
        self.label_15.setText(_translate("mainWindow", "€ / kWh"))
        self.label_20.setText(_translate("mainWindow", "Charge efficiency"))
        self.label_21.setText(_translate("mainWindow", "per unit"))
        self.label_14.setText(_translate("mainWindow", "Unitary cost"))
        self.label_16.setText(_translate("mainWindow", "Min state of charge"))
        self.label_18.setText(_translate("mainWindow", "per unit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InputTab), _translate("mainWindow", "Input"))
        self.groupBox_5.setTitle(_translate("mainWindow", "Plot results"))
        self.plot_results_pushButton.setText(_translate("mainWindow", "Plot"))
        self.groupBox_6.setTitle(_translate("mainWindow", "Optimization"))
        self.size_simulate_pushButton.setText(_translate("mainWindow", "Size facilities"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SimulationTab), _translate("mainWindow", "Simulation"))
        self.progress_label.setText(_translate("mainWindow", "Progress..."))
        self.cancel_pushButton.setText(_translate("mainWindow", "Cancel"))
        self.menuProject.setTitle(_translate("mainWindow", "Project"))
        self.menuAbout.setTitle(_translate("mainWindow", "Help"))
        self.actionOpen_file.setText(_translate("mainWindow", "Open file"))
        self.actionOpen_file.setShortcut(_translate("mainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("mainWindow", "Save"))
        self.actionSave.setShortcut(_translate("mainWindow", "Ctrl+S"))
        self.actionNew_project.setText(_translate("mainWindow", "New project"))
        self.actionNew_project.setShortcut(_translate("mainWindow", "Ctrl+N"))
        self.actionAbout.setText(_translate("mainWindow", "About"))

from .matplotlibwidget import MatplotlibWidget
# import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

